### ISSUE TITLE
Identifier of KeyCloak Authentication Realm

### ISSUE THREAD

**Issue by chortels** [flytreeleft/nexus3-keycloak-plugin#11]
Hi, 

I'm using KeyCloak plugin with Nexus 3.14. I'd like to automate the enabling of the Keycloak Authentication Realm through a groovy script, like the one that is indicated here: https://github.com/rgl/nexus-vagrant/blob/master/provision/provision-nexus/src/main/groovy/provision.groovy

In this file, for example, to enable the npm Bearer Token Realm the command used is (see line 102)

`realmManager.enableRealm("NpmToken")`

I'd like to know which is the string that I have to pass as parameter to realmManager.enableRealm to automate the enabling of Keycloak Authentication Realm.

Thanks for your attention. Regards.

**Comment by flytreeleft** [comment]
It should be `org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm`.
