### ISSUE TITLE
Using more than one realm to authenticate in Nexus

### ISSUE THREAD

**Issue by chortels** [flytreeleft/nexus3-keycloak-plugin#12]
Hi, 

I'd like to know if it is possible to configure more than one realm to authenticate against Nexus. I'll explain you the situation: in our company we have the nominal users, that are present in the active directory and, also, some "artificial users" that we create to do some activities like, for example, deploying artifacts to Nexus from Jenkins. These users are called "integration users" and cannot be related to any real user. For this reason, we must use two different realms, in order not to mix real users (those who are present in the Active Directory) and the artificial users. Is this possible?

Thank you for your attention, 

Regards.

**Comment by flytreeleft** [comment]
Maybe, it isn't so easy to get such goal. But, I will think about it seriously.

**Comment by chortels** [comment]
Thanks for your early answer @flytreeleft . My first idea was adding another entry to keycloak.json file with the configuration of the External Users realm, but with no success :(.

**Comment by flytreeleft** [comment]
@chortels The `keycloak.json` is parsed by Keycloak library, and only can contain one entry in it.

Of course, the plugin can bread and parse `keycloak.json` by itself, but it still faces some problems, such as:
- How to process the same username in different Keycloak realms.
- How to show and distinguish realm roles/groups for different Keycloak realms.

Maybe, we can create another Nexus3 realm which has different name in runtime? I will verify the possibility soon.

**Comment by chortels** [comment]
Thanks @flytreeleft . I'm looking forward to making this feature real!

**Comment by chortels** [comment]
Hi @flytreeleft . Any news about this feature? :)

Regards!

**Comment by flytreeleft** [comment]
@chortels It still needs more time, I will start to work on it at this weekend. Very sorry for my delay! :-(

**Comment by flytreeleft** [comment]
@chortels There are some difficulties to support multiple Keycloak realms. I tried to accomplish it, but was failed. I will try other possible way.

Before accomplishing it, you can create new **artificial users** in Nexus3 directly.

**Comment by flytreeleft** [comment]
@chortels I just submitted a implement for multiple Keycloak realms in https://github.com/flytreeleft/nexus3-keycloak-plugin/tree/feature-multi-realms , you can try it with https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/download/0.3.3-pre0-SNAPSHOT/nexus3-keycloak-plugin-0.3.2-SNAPSHOT.jar

**Comment by flytreeleft** [comment]
@chortels There is another implement in https://github.com/flytreeleft/nexus3-keycloak-plugin/tree/feature-multi-realms-with-redundance , you can try it with https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/download/0.3.3-pre1-SNAPSHOT/nexus3-keycloak-plugin-0.3.2-SNAPSHOT.jar

**Comment by flytreeleft** [comment]
It's already implemented via creating multiple [KeycloakAuthenticatingRealm.java](https://github.com/flytreeleft/nexus3-keycloak-plugin/blob/master/src/main/java/org/github/flytreeleft/nexus3/keycloak/plugin/KeycloakAuthenticatingRealm.java) classes, and the new version [0.3.3-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.3.3-SNAPSHOT) was released, it can be used directly.

Please read [Multiple Keycloak Realms](https://github.com/flytreeleft/nexus3-keycloak-plugin#multiple-keycloak-realms) to see how to configure the multiple Keycloak realms.
