### ISSUE TITLE
Not navigating to Keycloak url

### ISSUE THREAD

**Issue by rihtak06** [flytreeleft/nexus3-keycloak-plugin#16]
I followed the steps jar,keycloak.json,and start.properties and also  can see thekeycloak bundles and  realm in the ui but when i click sign in its not navigating to keycloak url still its opening default login.

**Comment by flytreeleft** [comment]
@rihtak06 Yes, the Nexus3 will not redirect to the Keycloak in the browser, it just give you the default login UI and verify the username/password in the background via calling the Keycloak's API.
