### ISSUE TITLE
Two-factor (OTP) support?

### ISSUE THREAD

**Issue by tcnh** [flytreeleft/nexus3-keycloak-plugin#17]
We use keycloak, but enforce usage of an authentication code generator to log in. Nexus however tries authenticating with user/password only, resulting in a failed logon.

Also , already having a logged in session still requires a separate login on nexus. Is this something that we can circumvent some way?

**Comment by flytreeleft** [comment]
@tcnh Sorry for late reply :(

I'm not sure about it, because Nexus3 do authenticating in background via invoking Keycloak's API right now.

Maybe we can get the OTP Token from the request header and verify it in background. I'll add it to the TODO list and confirm whether it can be done or not.

**Comment by flytreeleft** [comment]
@tcnh A new version [0.3.4-pre0-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.3.4-pre0-SNAPSHOT) is released, it supports to use Keycloak as SSO provider, it maybe will help you, you can have a try.

Please read [Single Sign On (SSO)](https://github.com/flytreeleft/nexus3-keycloak-plugin#single-sign-on-sso) for more details.

**Comment by tcnh** [comment]
Cool! I will have a look

**Comment by flytreeleft** [comment]
Just close the inactive issue. If there are any more problems, please just let me know :).
