### ISSUE TITLE
Unexpected response from server: 403 / Forbidden

### ISSUE THREAD

**Issue by 0x218** [flytreeleft/nexus3-keycloak-plugin#19]
Steps I did in my Oracle Linux vm: - 
1.   Dowloaded and placed nexus3-keycloak-plugin-0.3.3-SNAPSHOT.jar in "/apps/nexus3/nexus-3.16.1-02/system/org/github/flytreeleft/nexus3-keycloak-plugin/0.3.3-SNAPSHOT".

2.   Added "reference\:file\:org/github/flytreeleft/nexus3-keycloak-plugin/0.3.2-SNAPSHOT/nexus3-keycloak-plugin-0.3.2-SNAPSHOT.jar = 200" as the last stanza in /apps/nexus3/nexus-3.16.1-02/etc/karaf/startup.properties

3.   Created client realm in KeyCloak and pasted its OIDC content into /apps/nexus3/nexus-3.16.1-02/etc/keycloak.json

4.  Started Nexus3 ./bin/nexus start.  
      * Added Keycloak Authentication Realm into Active realms.  
      * Under Roles, Create role -> External role mapping -> Keycloak 
... and I get "Unexpected response from server: 403 / Forbidden".  

Please note, I can still create the role, people can login to Nexus3 with KeyCloak authentication, but KeyCloak users are getting same "Unexpected response from server: 403 / Forbidden" upon clicking anything (Welcome, Browse, Refresh, Profile ).  Also KeyCloak user is not getting privileges (ex: admin privilege) that I'm trying to map with the role.

Log snippet is attached.  Please advise what am I missing.

[nexus3_error_adding_keycloak_role.txt](https://github.com/flytreeleft/nexus3-keycloak-plugin/files/3153603/nexus3_error_adding_keycloak_role.txt)

**Comment by flytreeleft** [comment]
@0x218 Maybe, you forgot to configure `Service Account Roles` of the Nexus3 client in Keycloak. You can check that with reading the section [Configure Keycloak realm client](https://github.com/flytreeleft/nexus3-keycloak-plugin#4-configure-keycloak-realm-client).

**Comment by 0x218** [comment]
@flytreeleft Thank you much for looking into this issue.  I believe issue is not with KeyCloak configuration as it follows [Configure Keycloak realm client](https://github.com/flytreeleft/nexus3-keycloak-plugin#4-configure-keycloak-realm-client).  Please see the screenshot.

[developer@lab nexus-3.16.1-02]$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)


![image](https://user-images.githubusercontent.com/38358669/57384914-09255800-7177-11e9-94b6-e41ffa295cc9.png)

**Comment by 0x218** [comment]
@flytreeleft thank you for looking into  this.  I had a typo in one my nested folder created for plugin.  Once that is resolved, my issue is gone.

**Comment by 0x218** [comment]
@flytreeleft thank you for looking into  this.  I had a typo in one my nested folder created for plugin.  Once that is resolved, my issue is gone.

**Comment by 0x218** [comment]
@flytreeleft thank you for looking into this. As pointed out by @vidaks I believe the plugin works well in older version of KeyCloak.  I was getting issue with KeyCloak v4.8.2. and then I reconfigured it to a lower version (3.4.3) and the issue is gone.  @vidaks thank you.
