### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by jotacv** [flytreeleft/nexus3-keycloak-plugin#20]
First of all thanks for the great job and the great plugin! Awesome work.

We are trying to use keycloack not only to ease management of users, roles and such but also as a Single Sign On provider. Is this feature implemented?

Currently our users need to login only to keycloack to use all of the other tools but Nexus3.

Thanks for your time.

**Comment by flytreeleft** [comment]
@jotacv It seems that Nexus doesn't support SSO directly. So the better way maybe is doing authentication via using reverse proxy in front of Nexus, just like [How to Configure Request Header Authentication in Nexus with Apache](https://support.sonatype.com/hc/en-us/articles/214942368-How-to-Configure-Request-Header-Authentication-in-Nexus-with-Apache).

I will check what this plugin need to do for supporting reverse proxy authentication, and write the document for illustrating how to configure that.

**Comment by flytreeleft** [comment]
@jotacv I have already released a new version [0.3.4-pre0-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.3.4-pre0-SNAPSHOT) which supports SSO. You can have a try.

More details is [here](https://github.com/flytreeleft/nexus3-keycloak-plugin#single-sign-on-sso).

**Comment by flytreeleft** [comment]
Just close the inactive issue. If there are any more problems, please just let me know :).
