### ISSUE TITLE
Update plugin for Keycloak 6

### ISSUE THREAD

**Issue by IMbiea** [flytreeleft/nexus3-keycloak-plugin#23]
Hello, I was wondering if you've tested, with KeyCloak Version 6.x 

I'm specifically working with https://github.com/jboss-dockerfiles/keycloak/tree/1cd6becd9b6162d4677fb3d0c00be239d921d004

**Comment by flytreeleft** [comment]
@IMbiea Not yet, but I think the APIs should be compatible with v4.5.x, so the plugin should work well with v6.x.

**Comment by IMbiea** [comment]
need to test more... but so far.. Works with 6.0.1!

**Comment by flytreeleft** [comment]
@IMbiea Thanks, I will do some tests with v6.x.

**Comment by flytreeleft** [comment]
@IMbiea This plugin will work well with Keycloak 6.x. If there is any problem, please just open an issue, I will handle it as soon as possible.

**Comment by IMbiea** [comment]
I can open an issue... But am curious.. (and sorry for my ignorance...) Is it not possible for Nexus via the plug-in to proxy/ask if OTP is enabled?  I can't get that to work.

**Comment by flytreeleft** [comment]
About OTP will be answered in #24
