### ISSUE TITLE
Assitance with plugin and OTP

### ISSUE THREAD

**Issue by IMbiea** [flytreeleft/nexus3-keycloak-plugin#24]
KeyCloak: 6.0.1
Nexus3: OSS 3.17.0-01
Plugin: 0.3.4

When I enable OTP for a user associated with my nexus client, and try to authenticate to nexus I get:

` #033[0m#033[33m15:34:38,397 WARN  [org.keycloak.events] (default task-20) type=LOGIN_ERROR, realmId=Test, clientId=nexus3, userId=531c6fe4-0644-4f86-9909-dff8b713cb02, ipAddress=10.205.228.120, error=invalid_user_credentials, auth_method=openid-connect, grant_type=password, client_auth_method=client-secret, username=test-user`

**Comment by IMbiea** [comment]
Is this possible?  i.e. I don't get a redirect to the keycloak webpage (is that an SAML 2.0 thing?).. I just get the default nexus login page.. so will it/can it 'pop' to ask about OTP?

**Comment by flytreeleft** [comment]
@IMbiea Yes, it is already achieved in the version 0.3.4+. But you need to setup a reverse proxy before the Nexus3 server for enabling [Single Sign On (SSO)](https://github.com/flytreeleft/nexus3-keycloak-plugin#single-sign-on-sso).

**Comment by flytreeleft** [comment]
Close the inactive issue, if there still are some problems, please just make a comment or create a new issue :)
