### ISSUE TITLE
Any possible help on ideas for nginx reverse proxy with vouch/vouch-proxy

### ISSUE THREAD

**Issue by IMbiea** [flytreeleft/nexus3-keycloak-plugin#27]
Sorry this might be way out of scope for an "issue"..

I do see your nginx.conf examples.. However in my docker env.. I really can't use lua.  Plus, we are using [vouch](https://github.com/vouch/vouch-proxy) for a few other projects.

I've got my nginx file that looks like this...

```nginx
server {
    listen 80 ;
    server_name repo.test.com
    root /var/www/html/;
    client_max_body_size 1G;


    auth_request /validate;

    location = /validate {
      proxy_pass http://vouch.test.com:9090/validate;

      proxy_set_header Host $http_host;

      proxy_pass_request_body off;
      proxy_set_header Content-Length "";

      auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;

      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
      proxy_buffer_size          128k;
      proxy_buffers              4 256k;
      proxy_busy_buffers_size    256k;
    }

    error_page 401 = @error401;

    location @error401 {
        return 302 http://login.test.com/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }

    location / {
      proxy_pass http://nexus:8081;

      proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Keycloak-Sec-Auth $http_x_remote_user:$http_x_remote_user_access_token;
      proxy_hide_header X-Remote-User-Access-Token;
    }
}

server {
    listen 80 default_server;
    server_name login.test.com;
    location / {
       proxy_pass http://vouch.test.com:9090;
       proxy_set_header Host login.factory.caci.com;
       proxy_buffer_size          128k;
       proxy_buffers              4 256k;
       proxy_busy_buffers_size    256k;
    }
}
```

It works... (as far as I get though the proxy/keycloak and I'm presented with my nexus page... However I'm doing something wrong here.. as far as it allowing me to login without an additional set of credentials the nexus login page.

Using: nexus3-keycloak-plugin-0.3.4-SNAPSHOT.jar built into my Docker image.

**Comment by IMbiea** [comment]
And once I login, yes everything works PERFECT as far as roles and the keycloak plugin.. I'm just stuck on how to get the reverse proxy to work, and pass through my auth token.

**Comment by flytreeleft** [comment]
@IMbiea Sorry, I am not familiar with [Vouch Proxy](https://github.com/vouch/vouch-proxy), but I will try to find the way how to integrate this plugin with it.

**Comment by IMbiea** [comment]
@flytreeleft   Sorry I'm very newbie/ignorant here on this.  

Am I right in saying... That in theory in the nginx config where I would ask for validation (i.e. their code example is...

```nginx
server {
    listen 443 ssl http2;
    server_name protectedapp.yourdomain.com;
    root /var/www/html/;

    ssl_certificate /etc/letsencrypt/live/protectedapp.yourdomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/protectedapp.yourdomain.com/privkey.pem;

    # send all requests to the '/validate' endpoint for authorization
    auth_request /validate;

    location = /validate {
....

      # optionally add X-Vouch-User as returned by Vouch Proxy along with the request
      auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
```

That I would ALSO try to get the access token during that 'phase'

So that during the portion of the nginx config where I do my **proxy_pass**

I just do something like...

```nginx
proxy_set_header X-Vouch-User $auth_resp_x_vouch_user:$some_token;
```

i.e. I "tried" to do:

```nginx
auth_request_set $auth_resp_x_vouch_idp_accesstoken $upstream_http_x_vouch_idp_accesstoken;
```
but that didn't work, so i could not in turn do the "set"

**Comment by flytreeleft** [comment]
@IMbiea Just following these steps:

- Update this plugin to the version [0.3.4-pre2-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.3.4-pre2-SNAPSHOT).

- Modify your Vouch Proxy configuration to make sure the username and access token of Keycloak can be passed to Nginx:

```yaml
vouch:
  # ...
  domains:
    - <user's email domain>
    - ... # other domain or '<ip address>:<port>'
  headers:
    # ...
    # set access token to the header 'X-Vouch-IdP-AccessToken'
    accesstoken: X-Vouch-IdP-AccessToken
    # ...
  # ...
```

- Passing the Vouch user (`$upstream_http_x_vouch_user`) and access token (`$upstream_http_x_vouch_idp_accesstoken`) which are provided by Vouch Proxy to Nexus3:

```nginx
server {
    # ...
    location / {
        auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
        auth_request_set $auth_resp_x_vouch_idp_accesstoken $upstream_http_x_vouch_idp_accesstoken;

        proxy_set_header Host $host;
        proxy_set_header X-Keycloak-Sec-Auth $auth_resp_x_vouch_user:$auth_resp_x_vouch_idp_accesstoken;
        proxy_hide_header X-Remote-User-Access-Token;

        proxy_pass http://nexus:8081;
    }
    # ...
}
```

Have a good luck! :)

**Comment by flytreeleft** [comment]
@IMbiea See more details in [vouch-proxy/config.yml](https://github.com/flytreeleft/nexus3-keycloak-plugin/blob/master/develop/vouch-proxy/config.yml) and [vhost.d/nexus3-behind-vouch-proxy.conf](https://github.com/flytreeleft/nexus3-keycloak-plugin/blob/master/develop/nginx-gateway/vhost.d/nexus3-behind-vouch-proxy.conf)

**Comment by IMbiea** [comment]
@flytreeleft   I did some testing yesterday.. and YES!  It appears to work great!

I tested with 3.17.0,, and that appears to work!  

Two questions:
1) If voucher can patch to be able to pass along username instead of e-mail... Do you feel this will still work? ( this is really my preference)
2) I did try with 3.18.1   No success yet, but I didn't dig really deep either.

Thanks!
-Ira

**Comment by flytreeleft** [comment]
@IMbiea If you want to pass username to Nexus3, you need to:

- Add the following segments to your Vouch Proxy configuration:

```yaml
vouch:
  # ...
  headers:
    claims:
    - groups
    - preferred_username # which means the username (not email)
    # ...
  # ...
```

- And change `$upstream_http_x_vouch_user` to `$upstream_http_x_vouch_idp_claims_preferred_username` in your Nginx configuration:

```nginx
auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_idp_claims_preferred_username;
```

PS: The version v3.18.1 of Nexus3 can work well in my testing environment, maybe you should find the clue in the logs :)
