### ISSUE TITLE
Realm Role Support

### ISSUE THREAD

**Issue by hypery2k** [flytreeleft/nexus3-keycloak-plugin#3]
Did you plan to support Realm roles instead of just client roles?

**Comment by flytreeleft** [comment]
Sorry for late reply :-(.

There is no thus plan yet.

But I think there will be different roles between the different clients, and the same name role in two clients maybe have different users.

Actually, the [Realm Roles](https://www.keycloak.org/docs/latest/server_admin/index.html#realm-roles) should be used as the roles of Keycloak to grant its permissions to the realm users.

Also we can define some composite roles which are associated with the realm roles for our clients to reuse roles and grants.

So defining and mapping the client roles for clients maybe is a better way than using the realm roles directly.

**Comment by hypery2k** [comment]
I understand your point, but we decided to use global realm roles to be used across all applications. Would be great that this plugin would support that.
Would you open to accept a PR which enables this?

**Comment by flytreeleft** [comment]
@hypery2k Yes, any PR will be welcome.

**Comment by flytreeleft** [comment]
@hypery2k The version [0.3.1-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.3.1-SNAPSHOT) already supports the Realm roles mapping. You can have a try.
