### ISSUE TITLE
configure keycloak with nexus automatically

### ISSUE THREAD

**Issue by aliartiza75** [flytreeleft/nexus3-keycloak-plugin#36]
Hi,
Thank you for this plugin. What I really want to know is how all these steps can be done automatically as it contains a lot of manual steps, which is not acceptable in my current scenario.

Thank you

**Comment by marctanguy** [comment]
Hello @aliartiza75 

I don't really understand the point of your question. The readme describes the differents steps to deploy/configure this plugin on the Nexus server.
It's up to you to choose the way to automise these actions. We use puppet to deploy plugin and configuration files. You can also use ansible, shell, etc ....
To automatically configure Keycloak you can use REST api of Keycloak :
- create REALM
- create Nexus client in created REALM
- create role in nexus client
- assign role to user
These parts are also managed in our puppet code.

For me, the only manual option to configure is in Nexus when you have to select the keycloak realm in REALM option.

Regards
Marc

**Comment by aliartiza75** [comment]
Thank you @marctanguy, for your input. I will look at how the nexus part can be automated.

**Comment by flytreeleft** [comment]
Thanks @marctanguy . If it is possible, you can share your automatic scripts :).

**Comment by aliartiza75** [comment]
@flytreeleft read the api endpoints for nexus and make a rest call using curl for each of the tasks you want to automate.

**Comment by flytreeleft** [comment]
@aliartiza75 Yes, calling API via `curl` is a good idea. Thank you! :)
