### ISSUE TITLE
No Roles from keycloak

### ISSUE THREAD

**Issue by hypery2k** [flytreeleft/nexus3-keycloak-plugin#4]
Did you every experienced issues that the roles of a user weren't handed over the Nexus?

**Comment by flytreeleft** [comment]
Not yet until now. You can give more details, maybe I can find some clues to fix it.

**Comment by hypery2k** [comment]
we have to explizit set the client roles for each user.
Composition on realm role level isn't working.

So we have overall admins, which should have also admin access to nexus. Let's call this group **platform-admin** In nexus we have a mapping role **nexus-admin** which is read from a client role **app-admin** in the nexus client
If I say in the roles definition for **platform-admin** it's including **app-admin** of the nexus client it's not working for all users. But if I assign all users to **app-admin** role of the nexus client it's working

**Comment by flytreeleft** [comment]
I think this isn't an error or bug, it's working as the expected.

As you know, until now, Nexus can only see the client roles which are defined for the nexus client in Keycloak, and the role `platform-admin` will be unkown to Nexus.

So the user who is assigned `platform-admin` role but isn't assigned `app-admin` will not have the `nexus-admin` role.

For now, the better way is to assign the nexus's client role to every user. And I am thinking about how to support the realm roles, but it's not very clear, and I have to find some free time to do that :-(
