### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by Hokwang** [flytreeleft/nexus3-keycloak-plugin#40]
Hello.

Please update readme.md install_path based with docker image.

Refer to https://hub.docker.com/r/sonatype/nexus3,
installation of Nexus is to /opt/sonatype/nexus.
A persistent directory is /nexus-data.

Thanks,

**Comment by flytreeleft** [comment]
@Hokwang Thanks, I will update the readme as soon as possible.

**Comment by flytreeleft** [comment]
@Hokwang Sorry, I didn't found the place where needs to modify for the two directory. It seems that the two paths aren't  mentioned or are already changed in the docker container creating scripts.

Please just tell me the exact place where should be updated. Thanks!
