### ISSUE TITLE
Update plugin for Keycloak 9

### ISSUE THREAD

**Issue by DrGonzoIII** [flytreeleft/nexus3-keycloak-plugin#42]
Is there any plans to make it compatible with Keycloak 9?

**Comment by flytreeleft** [comment]
@DrGonzoIII Thanks for your advice, I will do some tests for it in couple of days.

**Comment by flytreeleft** [comment]
@DrGonzoIII The version [0.4.0-prev1-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.4.0-prev1-SNAPSHOT) is compatible with Keycloak 9. You can try it.

**Comment by DrGonzoIII** [comment]
Tested with Nexus 3.22.0-02 and Keycloak 9 
Thank you!!
