### ISSUE TITLE
Help on OTP/MFA and SSO

### ISSUE THREAD

**Issue by IMbiea** [flytreeleft/nexus3-keycloak-plugin#48]
Hello, I wanted your input on the use of SSO with MFA and use of the CLI..

i.e. I've been able to use your plugin with Keycloak/SSO  (via nginx and vouch proxy)

I can get the redirect to the IDP, and am able to use MFA (username/pass and authy), and then I'm redirected back to nexus, and can login!!

However, this breaks when attempting to auth via a developer workstation i.e. mvn cli.

Do you have ideas/recommendations on use?

**Comment by IMbiea** [comment]
I can use a different keycloak realm and hit that endpoint to bypass SSO/Vouch proxy.. but I guess it would be awesome if nexus had the free token realm   :-(

**Comment by flytreeleft** [comment]
@IMbiea Sorry for so late reply, I didn't get the notification from github :(.

Actually, we should use different authorization verifications for the web users and the CLI users when enabling SSO.

The SSO should be disabled temporarily when the HTTP header `Authorization` is specified or `User-Agent` is Maven or Docker. For Nginx, its configuration should be like (see [develop/nginx-gateway/vhost.d/nexus3.conf#L19](https://github.com/flytreeleft/nexus3-keycloak-plugin/blob/master/develop/nginx-gateway/vhost.d/nexus3.conf#L19)):
```nginx
        set $oidc_disabled "false";
        # Disable OIDC when using maven client
        if ($http_user_agent ~* "^(Apache-Maven|docker)/.+$") {
            set $oidc_disabled "true";
        }
        # And disable OIDC when the header Authorization was specified
        if ($http_authorization !~* "^$") {
            set $oidc_disabled "true";
        }
```

And the variable `$oidc_disabled` will be passed to the OIDC script and to skip token requests when it's `true`, like [develop/nginx-gateway/vhost.d/oidc.lua#L191](https://github.com/flytreeleft/nexus3-keycloak-plugin/blob/master/develop/nginx-gateway/vhost.d/oidc.lua#L191).

**Comment by WestFarmer** [comment]
@flytreeleft  So CLI users can't be authencatied by keycloak?

**Comment by flytreeleft** [comment]
@WestFarmer The CLI still can be working well, the command `mvn` will pass the username and password via the header `Authorization` which will be authenticated by Keycloak in the background.

**Comment by WestFarmer** [comment]
@flytreeleft that happens in the java code , right?

**Comment by flytreeleft** [comment]
@WestFarmer Yes, it is.

**Comment by flytreeleft** [comment]
Close the inactive issue, if it's not resolved, please just append the problem to this issue. Thanks :)
