### ISSUE TITLE
Tag on 0.4.0 version

### ISSUE THREAD

**Issue by olivier-jobert** [flytreeleft/nexus3-keycloak-plugin#49]
Hello,

I'm using your plugin in v0.3.4 which works very well and I would like to update it to the latest version to plug it with Keycloak version 9.

Although I prefer not to use a SNAPSHOT version, so do you need help for testing in order to deliver a GA version of v0.4.x ?

Thank you!

**Comment by flytreeleft** [comment]
@olivier-jobert Sorry for late reply.

Thanks for your advice. I just wasn't sure the latest version whether is stable or not. After waiting a so long time, I think it's time to release the new version v0.4.0 :)

**Comment by flytreeleft** [comment]
@olivier-jobert The version [v0.4.0](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/v0.4.0) has been released, you can get the artifacts from the release page or [GitHub Packages](https://github.com/flytreeleft/nexus3-keycloak-plugin/packages/25221?version=0.4.0).

**Comment by olivier-jobert** [comment]
Perfect, thanks a lot @flytreeleft !
