### ISSUE TITLE
Update plugin for Keycloak 4

### ISSUE THREAD

**Issue by devent** [flytreeleft/nexus3-keycloak-plugin#5]
The last stable version of Keycloak is 4.3.0.Final. It would be nice to update the plugin for Keycloak 4.
I tried to use the plugin as-is, but it will not work. I have updated keycloak-core to 4.3.0.Final in my own fork and now I can at least list the Keycloak roles. But a login is still not possible. No error is given.

I followed the guide in the readme.

1. add service account roles in the Keycloak client
2. added client roles "admin" and "developer" for the Keycloak client
3. created the groups "admin" and "developer" in Keycloak
4. assigned the client roles to the groups
5. joined users to the groups in Keycloak
6. added role mappings in Nexus to the Keycloak roles

Tried to sign-in as Keycloak user, but get login error. No other error message is available.

![grafik](https://user-images.githubusercontent.com/82924/44974037-c57eac80-af5e-11e8-9703-84a0e1331e57.png)

![grafik](https://user-images.githubusercontent.com/82924/44974565-5c983400-af60-11e8-99bc-cf6b2bbe1d0e.png)

![grafik](https://user-images.githubusercontent.com/82924/44974681-ada82800-af60-11e8-85e5-e104f8a70827.png)

**Comment by devent** [comment]
Update.
I had in Keycloak the option [x] Consent Required active.
After deactivating it, I was able to login in Nexus.
But the user does not have any privileges assign to him and the user is not listed under Users -> Source: Keycloak. So, that I can login using Keycloak is useless at the moment.

**Comment by flytreeleft** [comment]
@devent Can you past the pictures for the settings of `Clients -> nexus-anrisoftware-com -> Service Account Roles` and `Clients -> nexus-anrisoftware-com -> Roles`?

And, it seems that you bind the client roles to the realm groups, that is not supported right now. You should assign the client role to every user, like:

![](https://user-images.githubusercontent.com/1321315/45036116-307ad100-b08e-11e8-875d-fb61668addcf.png)

**Comment by devent** [comment]
As you requested.

Clients -> nexus-anrisoftware-com -> Service Account Roles

![grafik](https://user-images.githubusercontent.com/82924/45087025-e41ea800-b104-11e8-8afc-89260d31cf3b.png)

![grafik](https://user-images.githubusercontent.com/82924/45087049-f4368780-b104-11e8-899a-361d17426cf8.png)

Clients -> nexus-anrisoftware-com -> Roles

![grafik](https://user-images.githubusercontent.com/82924/45087075-06182a80-b105-11e8-9a2d-ef46f8663602.png)

**Comment by devent** [comment]
> And, it seems that you bind the client roles to the realm groups, that is not supported right now. You should assign the client role to every user, like:

I just removed the group from the user and assigned roles. Now the user can login and have the right permissions. Thank you. I will close the issue.

Will you update the nexus plugin to allow Keycloak groups?

**Comment by flytreeleft** [comment]
@devent Yes, I will do some works for it as soon as possible.

**Comment by Fantomatic** [comment]
Hi, I tried with the fork of devent and can't make it work, don't know if he pushed everything needed to make it work. If you could update your code, it would be deeply appreciated :) thanks for the good work anyway !

**Comment by flytreeleft** [comment]
@Fantomatic I will make it support the realm roles and groups first, then try to upgrade the version of Keycloak. This will need more time, but I will finish them as soon as possible.

**Comment by flytreeleft** [comment]
@Fantomatic @devent Hi, I have already upgraded the Keycloak to 4.x and it's compatible with Keycloak 3.x. All of you can try the new version [0.3.0-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.3.0-SNAPSHOT).
