### ISSUE TITLE
Is RUT realm needed 

### ISSUE THREAD

**Issue by WestFarmer** [flytreeleft/nexus3-keycloak-plugin#50]
Hi I see somewhere say we need to activate RUT realm to make this plugin work, is that true?

**Comment by flytreeleft** [comment]
@WestFarmer There is no need to activate RUT realm. If you want to enable [Single Sign On](https://github.com/flytreeleft/nexus3-keycloak-plugin#single-sign-on-sso), just follow the guide :).
