### ISSUE TITLE
KeyCloak 10 Support

### ISSUE THREAD

**Issue by DRLDoom** [flytreeleft/nexus3-keycloak-plugin#52]
Can the this be bumped to support KeyCloak 10?

**Comment by flytreeleft** [comment]
@DRLDoom I haven't test it, you can try it by yourself.

And based on the tests which were done by @wilderk at issue [#51](https://github.com/flytreeleft/nexus3-keycloak-plugin/issues/51#issuecomment-654303289), this plugin will work well with Keycloak 10.x.

**Comment by ggdn** [comment]
On my side the plugin is fully working with keycloak 10.0.0.2 and nexus 3.19.1-01 ;)

**Comment by flytreeleft** [comment]
@ggdn Good news, thanks for your feedback :)

**Comment by flytreeleft** [comment]
Close the inactive issue, if this plugin has any problem with Keycloak 10.x, just reopen this issue or create a new one. Thanks :)
