### ISSUE TITLE
0.5.0-SNAPSHOT Release Not found

### ISSUE THREAD

**Issue by josedev-union** [flytreeleft/nexus3-keycloak-plugin#55]
Hi team.
I cannot find 0.5.0-SNAPSHOT release at the release page.
Please let me know where I can find it.
Regards.

**Comment by flytreeleft** [comment]
@josedev-union There are no functional or bug-fixed code changes in 0.5.0, just use the latest version [v0.4.0](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/v0.4.0).

**Comment by josedev-union** [comment]
ok, thanks

**Comment by josedev-union** [comment]
looking forward to 0.5.0  release soon...
Regards.
