### ISSUE TITLE
Username with special charater leads authentication broken

### ISSUE THREAD

**Issue by josedev-union** [flytreeleft/nexus3-keycloak-plugin#57]
Hi Flytreeleft.
I am trying IdP brokering between keycloak and other IdPs.
So I integrated with google oauth and keycloak so I can now login to nexus by using google credential.
But the problem is when I first login with my google account, the keycloak requires user registration, you know.

At that time, my email address is inserted in the username field automatically.
Once i registered, then the auth failed.

Seems special charaters in username is leading fail in plugin code?
Not sure.
Please check this point.
Cheers.

**Comment by flytreeleft** [comment]
Close this issue, and trace it in #56 :)
