### ISSUE TITLE
Use Nexus plugin with Keycloak instance behind proxy

### ISSUE THREAD

**Issue by nbjohnson** [flytreeleft/nexus3-keycloak-plugin#63]
In my environment my Keycloak instance is behind a proxy. Even after setting the Nexus proxy settings and the jvm environment proxy settings, this keycloak plugin doesn't seem to respect any of those proxy settings. During initialization it just hangs at `KeycloakUserManager is starting`. Looking through the code a bit it seems that it may be that in the KeycloakAdminClient getHttp function the HttpClients builder does not include a routeplanner with the local environment proxy settings if they exist. Could either using local environment proxy variables or some other setting be implemented to allow this functionality? If I am missing something and there is already a way to support proxies with this plugin great I would love to hear it, but if not can this change be implemented? Thanks!

**Comment by flytreeleft** [comment]
@nbjohnson Please try [0.5.0-prev1-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.5.0-prev1-SNAPSHOT) which supports proxy setting, and set the proxy url in your `keycloak.json` as the following:

```json
{
    ...,
    "proxy-url": "http://<proxy-username>:<proxy-password>@<proxy-host>:<proxy-port>",
    ...
}
```

Note: the proxy server with HTTPS isn't supported yet.

**Comment by flytreeleft** [comment]
Close the inactive issue.
