### ISSUE TITLE
Generate Nexus access token after loggin in

### ISSUE THREAD

**Issue by rodrigoserracoelho** [flytreeleft/nexus3-keycloak-plugin#64]
Hello, first thanks for the keycloak plugin.
Now we are facing an issue.
**Scenario:** Since we disabled direct login on Nexus, we want to ask users to generate a nexus token, so they can then use for instance on Maven settings.
**Problem:** When the user clicks to generate a token on nexus, they get a popup asking to enter the credentials, but of course they are not on nexus anymore.
**Possible solution:** Is it possible at this stage to trigger the keycloak plugin, to authorize the user remotely on Keycloak?
I am available to implement the solution, i just wanted to have a chat with someone responsible for this plugin.

Thanks a lot.
Best,
Rodrigo

**Comment by flytreeleft** [comment]
@rodrigoserracoelho You can contact with me, or create a PR. :-)

**Comment by flytreeleft** [comment]
@rodrigoserracoelho Where is the place to generate the nexus token? And how does the user use it?

If you want a Keycloak remote token, you need to enable the [Single Sign On](https://github.com/flytreeleft/nexus3-keycloak-plugin#single-sign-on-sso).

**Comment by flytreeleft** [comment]
Close the inactive issue, if there still are more news, just please comment here. Thanks :)
