### ISSUE TITLE
SSO for all authentication requests

### ISSUE THREAD

**Issue by cuttingedge1109** [flytreeleft/nexus3-keycloak-plugin#66]
Hi @flytreeleft. Thank you for your plugin.
I have been enjoying your plugin for several months and working well.
But I found one issue - when I am admin and I try to change password of any user, it requires authentication again but not SSO, local authentication dialog popping up.
![image](https://user-images.githubusercontent.com/53085803/106004708-c5ddec00-60b3-11eb-9118-51e6e50d1822.png)

Is this a known issue?

**Comment by flytreeleft** [comment]
@cuttingedge1109 It's normal, the Nexus3 will re-authenticate the admin user by confirming its password, so you should make sure the admin user is a local user instead of a Keycloak user.

**Comment by cuttingedge1109** [comment]
Well, but other users are same.
Even though I logged in using keycloak user, it requires such a dialog to change the password.

**Comment by flytreeleft** [comment]
@cuttingedge1109 When does it happen for the normal user? After login or try to change other's password?

**Comment by cuttingedge1109** [comment]
The exact case is;
I logged in using keycloak user. This keycloak user is the admin.
Besides, there are several local users who have only read permissions on specific repositories.
I am a keycloak user but admin so I need to change the password of any local users.
When I try to change the local user's password, it requires to input new password and confirm password.
After that, it requires password for this admin user, keycloak user.

**Comment by flytreeleft** [comment]
@cuttingedge1109 Just login with a Nexus **local** admin user, then change the **local** users' password. **Do not** try to change the Nexus user's password via the Keycloak admin user.

PS: You should disable the SSO first before to change local users' password.

**Comment by cuttingedge1109** [comment]
I think it is fairly reasonable that there is no need to use local users once we use SSO. For our case, we remove the all permissions from the default admin local user and only use keycloak users.

Well, is there any milestone for this functionality? I am willing to contribute.

**Comment by flytreeleft** [comment]
@cuttingedge1109 :+1: Actually, I have no idea how to prevent to popup the confirm dialog, if you find the solution, just create a PR for that, it will be very useful, and thanks for your contribution too. :-)

**Comment by flytreeleft** [comment]
Close the inactive issue, if there still are more news, just please comment here. Thanks :)
