### ISSUE TITLE
Unexpected response from server: 401 / Unauthorized

### ISSUE THREAD

**Issue by cuttingedge1109** [flytreeleft/nexus3-keycloak-plugin#67]
Such logs are occurring continuously but not sure the reason. Before, I faced 401 and 403 errors and fixed but this error is a new one.
![image](https://user-images.githubusercontent.com/53085803/106435056-ad365300-6472-11eb-8d05-188d4ae5b2d3.png)

@flytreeleft Do you have any idea?

**Comment by flytreeleft** [comment]
@cuttingedge1109 Which version of this plugin did you use? And did you configure your Keycloak realm client permissions as the README guide?

**Comment by cuttingedge1109** [comment]
@flytreeleft Yes, I did.
The version is 0.4.1-SNAPSHOT which I contributed before. My old account is @josedev-union.

**Comment by flytreeleft** [comment]
@cuttingedge1109 How did you configure your gateway? Maybe, the gateway did not pass the auth token to the Keycloak correctly.

**Comment by cuttingedge1109** [comment]
Let me close it now.
The other users can login correctly but seems likely there are some malicious requests against the proxy.
