### ISSUE TITLE
"Effective Roles"  have no effect

### ISSUE THREAD

**Issue by boardend** [flytreeleft/nexus3-keycloak-plugin#7]
When assigning Keycloak-Roles to Keycloak-Users directly, the "Assigned Roles" get transferred/mapped correctly.

When assigning Keycloak-Roles to Keycloak-Groups, and adding Keycloak-Users to that Group, the "Effective Roles" don't get transferred/mapped in Nexus3.

Links:
- https://www.keycloak.org/docs/latest/server_admin/index.html#user-role-mappings
- https://www.keycloak.org/docs/latest/server_admin/index.html#groups-vs-roles

PS: I haven't testet Composite-Roles yet; They would also be listed as "Effective Roles", so my Guess is that this wouldn't work either?

**Comment by flytreeleft** [comment]
@boardend Yes, the composite roles and groups aren't supported yet :(. I will find the way to support all of them.

**Comment by boardend** [comment]
I've built a little test setup and confirm that composite roles do have the same problem.

But IMHO the solution is quite easy: In [getRealmRolesOfUser(..)](https://github.com/flytreeleft/nexus3-keycloak-plugin/blob/7721d3b67b18c894eca9194e4372072f26ec4034/src/main/java/org/github/flytreeleft/nexus3/keycloak/plugin/internal/KeycloakAdminClient.java#L210) "/composite" should be appended to the URL:

- [`GET /{realm}/users/{id}/role-mappings/realm`](https://www.keycloak.org/docs-api/4.5/rest-api/index.html#_getrealmrolemappings)
  - "Get realm-level role mappings"
- [`GET /{realm}/users/{id}/role-mappings/realm/composite`](https://www.keycloak.org/docs-api/4.5/rest-api/index.html#_getcompositerealmrolemappings)
  - "Get effective realm-level role mappings This will recurse all composite roles to get the result."

Probably the same fix is needed for [getRealmClientRolesOfUser(..)](https://github.com/flytreeleft/nexus3-keycloak-plugin/blob/7721d3b67b18c894eca9194e4372072f26ec4034/src/main/java/org/github/flytreeleft/nexus3/keycloak/plugin/internal/KeycloakAdminClient.java#L185), see [Get effective client-level role mappings This recurses any composite roles](https://www.keycloak.org/docs-api/4.5/rest-api/index.html#_getcompositeclientrolemappings)

@flytreeleft  Do you want to investigate further, or should I try to fix, test and submit a PR?

**Comment by flytreeleft** [comment]
@boardend It will be very glad and thankful if you can submit your PR(s) for that :)

**Comment by boardend** [comment]
I couldn't think of a good way to write unit/integration tests for the fix. But I did some manual testing as described in #8 

With version 0.3.0 I had the behavior that every unmapped role lead to an exception in nexus when a user with such a role assigned logged in (I'm not sure if it was the plugin or nexus3 itself...). So I ended up creating a role in nexus for every role that could possible be assigned in the realm or client (so even offline_access and uma_authorization). Finally  I fixed the issue by preventing full scope access form the client and only made those roles available that are relevant/mapped in nexus.
I don't know if this is still an issue in the current version. But this change would possible expose some new roles to an existing nexus3 installation..?

**Comment by flytreeleft** [comment]
@boardend Don't worry, I will check it!

**Comment by flytreeleft** [comment]
@boardend The new version [0.3.2-SNAPSHOT](https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/tag/0.3.2-SNAPSHOT-testing) now support the groups and composite roles already.

And your changes will not cause unexpected behavior. All realm roles and client roles existing in Keycloak will be exposed to Nexus3, and only the needed roles need to be mapped in Nexus3.

The unmapped Keycloak roles should not cause exceptions either. You can paste the exception stack information if it really happened.

Thanks for your PR :)

**Comment by flytreeleft** [comment]
@boardend By the way, I prepare the scripts in the directory `develop` for development. You can try it, maybe it will be helpful for you :)
