### ISSUE TITLE
How to use keycloak with machine users

### ISSUE THREAD

**Issue by faizanahmad055** [flytreeleft/nexus3-keycloak-plugin#9]
Does this plugin support for machine user authentication? I'm currently using keycloak proxy to do nexus authentication. From web ui authentication works fine. But when I try to upload a maven artifact it does not authenticate maven. So currently my setup authenticates the user from browser but does not authenticate the machine users. I wonder how this is handled in this plugin?

**Comment by flytreeleft** [comment]
@faizanahmad055 Do you mean that you can login Nexus3 via browser but can not upload artifacts via maven command like `mvn deploy`? If so, can you download artifacts by running `mvn compile` or `mvn install`?

If only uploading failed but downloading is successful, so I guess maybe you haven't granted the uploading privilege of Nexus3 to the user.

**Comment by flytreeleft** [comment]
@faizanahmad055 In Nexus3, the plugin will send requests to the Keycloak server and get the response data, this procedure is just same as what the browser does.
